services:
  ui:
    build:
      context: .
      dockerfile: packages/ui/Dockerfile
    env_file:
      - packages/ui/.env
    networks:
      - appnet
    restart: unless-stopped
    depends_on:
      - db-wait

  db-wait:
    image: bash:5.2
    command: bash -lc 'until echo > /dev/tcp/db/5432; do echo waiting for db; sleep 1; done'
    networks:
      - appnet

networks:
  appnet:
    external: true
